CREATE TABLE topicos(

id BIGINT NOT NULL AUTO_INCREMENT,
titulo VARCHAR(100) NOT NULL UNIQUE,
mensaje VARCHAR(500) NOT NULL,
Creacion datetime NOT NULL,
estatus VARCHAR(100) NOT NULL,
autor VARCHAR(30) NOT NULL,
curso VARCHAR(30) NOT NULL,
PRIMARY KEY(id)

);