CREATE TABLE usuarios(

id BIGINT NOT NULL AUTO_INCREMENT,
nombre VARCHAR(50) NOT NULL,
correo VARCHAR(60) NOT NULL UNIQUE,
login VARCHAR(50) NOT NULL UNIQUE,
clave VARCHAR(30) NOT NULL,
 PRIMARY KEY (id)
);