CREATE TABLE usuarios(

id BIGINT NOT NULL AUTO_INCREMENT,
nombre VARCHAR(50) NOT NULL,
correo VARCHAR(60) NOT NULL UNIQUE,
login VARCHAR(100) NOT NULL UNIQUE,
clave VARCHAR(500) NOT NULL,
rol INT NOT NULL,
 PRIMARY KEY (id)
);